# Generated by Django 3.0.5 on 2020-04-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klins',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='码值')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='名称')),
                ('data', models.CharField(blank=True, max_length=5000, verbose_name='内容')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
        ),
    ]
