# Generated by Django 3.0.5 on 2020-04-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Klins',
            new_name='test',
        ),
    ]
