# Generated by Django 3.0.5 on 2020-04-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_auto_20200428_2331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='Klins',
        ),
    ]
