# Generated by Django 3.0.5 on 2020-05-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0004_auto_20200502_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klins',
            options={'ordering': ['addtime']},
        ),
        migrations.AddField(
            model_name='klins',
            name='flag',
            field=models.CharField(blank=True, max_length=10, verbose_name='k线类型'),
        ),
    ]
