# Generated by Django 2.1 on 2020-05-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0005_auto_20200503_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klins',
            options={'verbose_name': 'K线信息表', 'verbose_name_plural': 'K线信息表'},
        ),
        migrations.AlterField(
            model_name='klins',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='klins',
            table='klins_info',
        ),
    ]
